### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by djberg96** [bnagy/rBuggery#4]
Please update the Wiki so that folks like me have a better idea of how to use this library.

**Comment by bnagy** [comment]
Hi Dan! Uh.. k? What would you like to see that's not already in `examples`? It's a debugger binding, obvs, so the possible uses are extremely broad - or you mean just basic hello world setup stuff?

**Comment by djberg96** [comment]
Yep, basic hello world would be good, plus whatever else you feel like adding from the examples.
