### ISSUE TITLE
cannot attach_kernel with event_callbacks

### ISSUE THREAD

**Issue by andyschmidt** [bnagy/rBuggery#5]
Hi,

when I try to call attach_kernel with event_callbacks the function (ruby process) stops immediately.

I'm running ruby 2.0 x86 on Win7 with rBuggery 1.1.1

Here's my code:

```
require 'buggery'

@debug_client ||= Buggery::Debugger.new
puts @debug_client

bp_callback=lambda { |args|
  puts "! hit BP"
  bp = DebugBreakpoint.new args[:breakpoint]
  0
}

exception_callback=lambda { |args|
  puts "! hit exception"
  exr = ExceptionRecord64.new args[:exception_record]
  code = "%8.8x" % exr[:code]

  1 # DEBUG_STATUS_GO
}

begin

  puts "  - set event callbacks"
  # if one of the following two lines is uncommented the attach_kernel call will quit without any
  # information
  #@debug_client.event_callbacks.add(:breakpoint => bp_callback, :exception => exception_callback)
  #@debug_client.event_callbacks.add(:breakpoint => bp_callback)
  puts "  - attach to kernel"
  @debug_client.attach_kernel('com:pipe,port=\\\\.\\pipe\\com_1,resets=0,reconnect')
  puts "  - break"
  @debug_client.break

rescue => bang
  puts '! something went wrong'
  puts bang
  puts bang.backtrace
  exit
end

print '.'
@debug_client.wait_for_event
puts @debug_client.execute ".sympath C:\\symbols"
#puts @debug_client.execute ".symfix c:\\symbols"
puts @debug_client.execute ".reload"
```

I couldn't find any documented kernel related limitations on EventCallbacks at MSDN.
I'm new to kernel debugging, so is this behaviour normal or a "bug" in rBuggery?

thanks,

andy

**Comment by bnagy** [comment]
Sounds like a bug. I don't know if I ever did any callback based kernel debugging. Can you try it with a direct event loop handler, like in `examples/kerntrace.rb`? If that works then I guess we're going to need to debug the debugger (which is a pain in the butt). Either way I won't be able to do much with this for a week or so, I'm off to NZ tomorrow for Kiwicon.

**Comment by andyschmidt** [comment]
SOLVED - the problem was the old version of windbg (6.3) on the system. With windbg 6.11 it works.

**Comment by bnagy** [comment]
Thanks a lot for following up with the solution! :)
